SELECT B.AUTHOR_ID
    , C.AUTHOR_NAME
    , B.CATEGORY
    , SUM(A.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES A
    , BOOK B
    , AUTHOR C
WHERE 1=1
    AND TO_CHAR(A.SALES_DATE, 'YYYY-MM-DD') LIKE '2022-01%'
    AND A.BOOK_ID = B.BOOK_ID
    AND B.AUTHOR_ID = C.AUTHOR_ID
GROUP BY B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY
ORDER BY 1, 3 DESC
;