SELECT C.CAR_ID
    , C.CAR_TYPE
    , ((100 - D.DISCOUNT_RATE) / 100) * (C.DAILY_FEE * 30) AS FEE
FROM
    (
        SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR A    
        WHERE A.CAR_ID NOT IN
            (
                SELECT B.CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
                WHERE TO_CHAR(START_DATE, 'YYYY--MM-DD') <= '2022-11-30'
                    AND TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-11-01'
            )
            AND A.CAR_TYPE IN ('SUV', '세단')
    ) C
, CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
WHERE 1 = 1
    AND C.CAR_TYPE = D.CAR_TYPE
    AND D.DURATION_TYPE = '30일 이상'
    AND ((100 - D.DISCOUNT_RATE) / 100) * (C.DAILY_FEE * 30) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC;