SELECT A.ID, A.NAME, A.HOST_ID
FROM PLACES A
WHERE 1=1
    AND A.HOST_ID IN (
        SELECT B.HOST_ID
        FROM PLACES B
        GROUP BY B.HOST_ID
        HAVING COUNT(B.HOST_ID) >= 2
    )
ORDER BY 1
;