SELECT C.HISTORY_ID
    , DECODE(C.DURATION_TYPE
             , NULL
             , (A.DAILY_FEE * (C.END_DATE - C.START_DATE + 1)), ((100 - D.DISCOUNT_RATE) / 100) * (A.DAILY_FEE * (C.END_DATE - C.START_DATE + 1))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
    , (SELECT B.HISTORY_ID
        , B.CAR_ID
        , B.START_DATE
        , B.END_DATE
        , CASE WHEN END_DATE - START_DATE + 1 >= 90 THEN '90일 이상'
             WHEN END_DATE - START_DATE + 1 >= 30 THEN '30일 이상'
             WHEN END_DATE - START_DATE + 1 >= 7 THEN '7일 이상'
             ELSE NULL
          END DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
      ) C
    , CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
WHERE 1 = 1
    AND A.CAR_ID = C.CAR_ID
    AND A.CAR_TYPE = '트럭'
    AND A.CAR_TYPE = D.CAR_TYPE(+)
    AND C.DURATION_TYPE = D.DURATION_TYPE(+)
ORDER BY 2 DESC, 1 DESC;
