SELECT C.APNT_NO, A.PT_NAME, C.PT_NO, B.MCDP_CD, B.DR_NAME, C.APNT_YMD
FROM PATIENT A
    , DOCTOR B
    , APPOINTMENT C
WHERE 1=1
    AND A.PT_NO = C.PT_NO
    AND B.DR_ID = C.MDDR_ID
    AND B.MCDP_CD = 'CS'
    AND C.APNT_CNCL_YN = 'N'
    AND TO_CHAR(C.APNT_YMD, 'YYYY-MM-DD') LIKE '2022-04-13%'
ORDER BY 6
;