SELECT TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24')) AS HOUR
    , COUNT(*) AS COUNT
FROM ANIMAL_OUTS A
WHERE 1=1
    AND TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24')) BETWEEN 9 AND 19
GROUP BY TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24'))
ORDER BY 1
