SELECT EXTRACT(MONTH FROM A.START_DATE) AS MONTH, A.CAR_ID, COUNT(A.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE A.CAR_ID IN (
    SELECT B.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    WHERE 1=1
        AND TO_CHAR(START_DATE, 'YYYY-MM-DD') BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY B.CAR_ID
    HAVING COUNT(B.CAR_ID) >= 5
)
AND TO_CHAR(START_DATE, 'YYYY-MM-DD') BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY EXTRACT(MONTH FROM A.START_DATE), A.CAR_ID
ORDER BY 1, 2 DESC