SELECT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A
WHERE 1 = 1
    AND A.CAR_TYPE = '세단'
    AND A.CAR_ID IN 
    (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE LIKE '%2022-10-%'
    )
ORDER BY A.CAR_ID DESC;
    