SELECT B.SCORE, B.EMP_NO, D.EMP_NAME, D.POSITION, D.EMAIL
FROM (
    SELECT A.EMP_NO
        , A.YEAR
        , SUM(A.SCORE) AS SCORE
    FROM HR_GRADE A
    GROUP BY A.EMP_NO, A.YEAR
    ORDER BY SUM(A.SCORE) DESC
    LIMIT 1
) B
, HR_DEPARTMENT C
, HR_EMPLOYEES D
WHERE 1=1
AND B.EMP_NO = D.EMP_NO
AND C.DEPT_ID = D.DEPT_ID




