SELECT A.BOARD_ID, A.WRITER_ID, A.TITLE, A.PRICE,
    CASE WHEN STATUS = 'SALE' THEN '판매중'
         WHEN STATUS = 'RESERVED' THEN '예약중'
         ELSE '거래완료'
    END STATUS
FROM USED_GOODS_BOARD A
WHERE 1=1
    AND CREATED_DATE LIKE '%2022-10-05%'
ORDER BY BOARD_ID DESC;