SELECT
    CONCAT('/home/grep/src/', A.BOARD_ID, '/', B.FILE_ID, B.FILE_NAME, B.FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD A
    ,USED_GOODS_FILE B
WHERE A.BOARD_ID = B.BOARD_ID
    AND A.VIEWS IN 
    (
        SELECT MAX(VIEWS)
        FROM USED_GOODS_BOARD
    )
ORDER BY B.FILE_ID DESC;