SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A
    , BOOK_SALES B
WHERE 1=1
    AND A.BOOK_ID = B.BOOK_ID
    AND TO_CHAR(B.SALES_DATE, 'YYYY-MM-DD') LIKE '2022-01%'
GROUP BY A.CATEGORY
ORDER BY 1
;